package com.acethewildfire.acesbs.block.entity;

import com.acethewildfire.acesbs.AcesBS;
import com.acethewildfire.acesbs.block.ModBlocks;
import com.acethewildfire.acesbs.block.entity.custom.EntropicEntanglerEntity;
import com.acethewildfire.acesbs.block.entity.custom.EntropicEvisceratorEntity;
import com.acethewildfire.acesbs.block.entity.custom.EntropicStabilizerEntity;
import net.minecraft.block.entity.BlockEntityType;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class ModBlockEntities {

    public static final BlockEntityType<EntropicStabilizerEntity> E_STABILIZER_BE =
            Registry.register(Registries.BLOCK_ENTITY_TYPE, Identifier.of(AcesBS.MOD_ID, "e_stabilizer_be"),
                    BlockEntityType.Builder.create(EntropicStabilizerEntity::new, ModBlocks.ENTROPIC_STABILIZER).build(null));
    public static final BlockEntityType<EntropicEvisceratorEntity> E_EVISCERATOR_BE =
            Registry.register(Registries.BLOCK_ENTITY_TYPE, Identifier.of(AcesBS.MOD_ID, "e_eviscerator_be"),
                    BlockEntityType.Builder.create(EntropicEvisceratorEntity::new, ModBlocks.ENTROPIC_EVISCERATOR).build(null));
    public static final BlockEntityType<EntropicEntanglerEntity> E_ENTANGLER_BE =
            Registry.register(Registries.BLOCK_ENTITY_TYPE, Identifier.of(AcesBS.MOD_ID, "e_entangler_be"),
                    BlockEntityType.Builder.create(EntropicEntanglerEntity::new, ModBlocks.ENTROPIC_ENTANGLER).build(null));

    public static void registerBlockEntities() {
        AcesBS.LOGGER.info("Registering Block Entities for " + AcesBS.MOD_ID);
    }


}
