package com.acethewildfire.acesbs.potion;

import com.acethewildfire.acesbs.AcesBS;
import com.acethewildfire.acesbs.effect.ModEffects;
import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.potion.Potion;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.entry.RegistryEntry;
import net.minecraft.util.Identifier;

public class ModPotions {

    public static final RegistryEntry<Potion> BLINDNESS = registerPotion("blindness", new Potion(new StatusEffectInstance(StatusEffects.BLINDNESS, 1200, 0)));
    public static final RegistryEntry<Potion> LEMON = registerPotion("lemon", new Potion(new StatusEffectInstance(ModEffects.LEMON, 1200, 0)));

    private static RegistryEntry<Potion> registerPotion(String name, Potion potion){
        return Registry.registerReference(Registries.POTION, Identifier.of(AcesBS.MOD_ID, name), potion);
    }

    public static void registerPotions(){
        AcesBS.LOGGER.info("Registering Mod Potions for " + AcesBS.MOD_ID);
    }
}
