package com.acethewildfire.acesbs.recipe;

import com.acethewildfire.acesbs.AcesBS;
import net.minecraft.recipe.RecipeSerializer;
import net.minecraft.recipe.RecipeType;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class ModRecipies {
    public static final RecipeSerializer<EntropicStabilizerRecipe> ENTROPIC_STABILIZER_SERIALIZER =
            Registry.register(Registries.RECIPE_SERIALIZER, Identifier.of(AcesBS.MOD_ID, "entropic_stabilizer"),
                    new EntropicStabilizerRecipe.Serializer());

    public static final RecipeType<EntropicStabilizerRecipe>  ENTROPIC_STABILIZER_TYPE =
            Registry.register(Registries.RECIPE_TYPE, Identifier.of(AcesBS.MOD_ID, "entropic_stabilizer"),
                    new RecipeType<EntropicStabilizerRecipe>() {
                        @Override
                        public String toString() {
                            return "entropic_stabilizer";
                    }
    });

    public static final RecipeSerializer<EntropicEvisceratorRecipe> ENTROPIC_EVISCERATOR_SERIALIZER =
            Registry.register(Registries.RECIPE_SERIALIZER, Identifier.of(AcesBS.MOD_ID, "entropic_eviscerator"),
                    new EntropicEvisceratorRecipe.Serializer());

    public static final RecipeType<EntropicEvisceratorRecipe>  ENTROPIC_EVISCERATOR_TYPE =
            Registry.register(Registries.RECIPE_TYPE, Identifier.of(AcesBS.MOD_ID, "entropic_eviscerator"),
                    new RecipeType<EntropicEvisceratorRecipe>() {
                        @Override
                        public String toString() {
                            return "entropic_eviscerator";
                        }
                    });

    public static final RecipeSerializer<EntropicEntanglerRecipe> ENTROPIC_ENTANGLER_SERIALIZER =
            Registry.register(Registries.RECIPE_SERIALIZER, Identifier.of(AcesBS.MOD_ID, "entropic_entangler"),
                    new EntropicEntanglerRecipe.Serializer());

    public static final RecipeType<EntropicEntanglerRecipe> ENTROPIC_ENTANGLER_TYPE =
            Registry.register(Registries.RECIPE_TYPE, Identifier.of(AcesBS.MOD_ID, "entropic_entangler"),
                    new RecipeType<EntropicEntanglerRecipe>() {
                        @Override
                        public String toString() {
                            return "entropic_entangler";
                        }
                    });

    public static void registerRecipes() {
        AcesBS.LOGGER.info("Registering Custom Recipes for " + AcesBS.MOD_ID);
    }
}
