package com.acethewildfire.acesbs.entity;

import com.acethewildfire.acesbs.AcesBS;
import com.acethewildfire.acesbs.entity.custom.CombustibleLemonEntity;
import com.acethewildfire.acesbs.entity.custom.FrenEntity;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class ModEntities {

    public static final EntityType<FrenEntity> FREN = Registry.register(Registries.ENTITY_TYPE,
            Identifier.of(AcesBS.MOD_ID, "fren"),
            EntityType.Builder.create(FrenEntity::new, SpawnGroup.MONSTER)
                    .dimensions(0.6F, 1.7F).build());

    public static final EntityType<CombustibleLemonEntity> C_LEMON = Registry.register(Registries.ENTITY_TYPE,
            Identifier.of(AcesBS.MOD_ID, "combustible_lemon"),
            EntityType.Builder.<CombustibleLemonEntity>create(CombustibleLemonEntity::new, SpawnGroup.MISC)
                    .dimensions(0.5F, 0.5F).build());


    public static void registerModEntities() {
        AcesBS.LOGGER.info("Registering Mod Entities for " + AcesBS.MOD_ID);
    }
}
