package com.acethewildfire.acesbs.particle;

import com.acethewildfire.acesbs.AcesBS;
import net.fabricmc.fabric.api.particle.v1.FabricParticleTypes;
import net.minecraft.particle.SimpleParticleType;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class ModParticles {

    public static final SimpleParticleType PURPLE_FLAME = registerParticles("purple_flame", FabricParticleTypes.simple(true));
    public static final SimpleParticleType GREEN_FLAME = registerParticles("green_flame", FabricParticleTypes.simple(true));

    private static SimpleParticleType registerParticles(String name, SimpleParticleType particleType){
        return Registry.register(Registries.PARTICLE_TYPE, Identifier.of(AcesBS.MOD_ID, name), particleType);
    }

    public static void registerModParticles() {
        AcesBS.LOGGER.info("Registering Mod Particles for " + AcesBS.MOD_ID);
    }
}
