package com.acethewildfire.acesbs.sounds;

import com.acethewildfire.acesbs.AcesBS;
import net.minecraft.block.jukebox.JukeboxSong;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.sound.SoundEvent;
import net.minecraft.util.Identifier;

public class ModSounds {
    public static final SoundEvent LIZARD = registerSoundEvent("lizard");
    public static final SoundEvent FART = registerSoundEvent("fart");
    public static final SoundEvent GRUMBLE = registerSoundEvent("grumble");
    public static final SoundEvent HOLY = registerSoundEvent("holy");
    public static final SoundEvent HOLY_S = registerSoundEvent("holy_s");
    public static final SoundEvent BRICKED_UP = registerSoundEvent("bricked_up");
    public static final SoundEvent SMOKING = registerSoundEvent("smoking");


//    public static final BlockSoundGroup LIZARD_SOUNDS = new BlockSoundGroup(1f, 1f, SoundEvents.BLOCK_WOOD_BREAK, SoundEvents.BLOCK_WOOD_STEP, SoundEvents.BLOCK_WOOD_PLACE, SoundEvents.BLOCK_WOOD_HIT, SoundEvents.BLOCK_WOOD_FALL)

    public static final SoundEvent CRAB_RAVE = registerSoundEvent("crab_rave");
    public static final RegistryKey<JukeboxSong> CRAB_RAVE_KEY =
            RegistryKey.of(RegistryKeys.JUKEBOX_SONG, Identifier.of(AcesBS.MOD_ID, "crab_rave"));

    private static SoundEvent registerSoundEvent(String name){
        Identifier id = Identifier.of(AcesBS.MOD_ID, name);
        return Registry.register(Registries.SOUND_EVENT, id, SoundEvent.of(id));
    }


    public static void registerSounds(){
        AcesBS.LOGGER.info("Registering Mod Sounds for " + AcesBS.MOD_ID);
    }

}
